### ISSUE TITLE
Bug while installing requirements.txt

### ISSUE THREAD

**Issue by amit-99** [amit-99/SE_Project2#13]
Master branch,

getting following error in console:
`Collecting json5>=0.9.5 (from scrapeops-scrapy==0.5.3->-r requirements.txt (line 46))
  Obtaining dependency information for json5>=0.9.5 from https://files.pythonhosted.org/packages/70/ba/fa37123a86ae8287d6678535a944f9c3377d8165e536310ed6f6cb0f0c0e/json5-0.9.14-py2.py3-none-any.whl.metadata
  Downloading json5-0.9.14-py2.py3-none-any.whl.metadata (10 kB)
INFO: pip is looking at multiple versions of scrapeops-scrapy to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 16), -r requirements.txt (line 35), -r requirements.txt (line 46) and itemadapter==0.1.0 because these package versions have conflicting dependencies.`

`The conflict is caused by:
    The user requested itemadapter==0.1.0
    itemloaders 1.0.3 depends on itemadapter>=0.1.0
    scrapy 2.3.0 depends on itemadapter>=0.1.0
    scrapeops-scrapy 0.5.3 depends on itemadapter>=0.4.0`

`To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict`

`ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by Yogesh31Hasabe** [comment]
Bug fixed by updating the corresponding versions of the specified libraries

**Comment by Yogesh31Hasabe** [comment]
Bug fixed by updating the corresponding versions of the specified libraries
